### ISSUE TITLE
Licence

### ISSUE THREAD

**Issue by Lymdun** [yaoling1997/GT-ToneMapping#2]
Hello, what is the licence of your code? thanks

**Comment by yaoling1997** [comment]
腾讯官方：您的信件已被成功接收~

**Comment by yaoling1997** [comment]
> Hello, what is the licence of your code? thanks

Thanks for your attention, I've created an MIT licence, have fun!

**Comment by Lymdun** [comment]
> Thanks for your attention, I've created an MIT licence, have fun!

Thanks you very much, I appreciate it!
